# Generated by Django 5.0.3 on 2024-03-16 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FlashcardModel',
            new_name='Flashcard',
        ),
    ]
