# Generated by Django 5.0.3 on 2024-03-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_rename_flashcardmodel_flashcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
