# Generated by Django 5.0.1 on 2024-01-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="flashcard",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
